"""empty message

Revision ID: 03342b464dd1
Revises: cc72ae956c6b
Create Date: 2021-10-08 08:47:23.568440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03342b464dd1'
down_revision = 'cc72ae956c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'description')
    # ### end Alembic commands ###
