"""empty message

Revision ID: 07414c247149
Revises: da6aa2e007c2
Create Date: 2021-10-06 17:58:59.509728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07414c247149'
down_revision = 'da6aa2e007c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('tipo', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'tratamiento', ['tipo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tratamiento', type_='unique')
    op.drop_column('tratamiento', 'tipo')
    # ### end Alembic commands ###
