"""empty message

Revision ID: 4186f52cfc47
Revises: d8ac1a8d76d2
Create Date: 2021-10-27 09:40:49.312506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4186f52cfc47'
down_revision = 'd8ac1a8d76d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('is_mutual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'is_mutual')
    # ### end Alembic commands ###
