"""empty message

Revision ID: 493a2bf3e014
Revises: 6397a210c2dc
Create Date: 2021-10-06 19:14:10.749824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493a2bf3e014'
down_revision = '6397a210c2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tratamiento', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
