"""empty message

Revision ID: 6397a210c2dc
Revises: d069f4d6b298
Create Date: 2021-10-06 19:12:01.769462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6397a210c2dc'
down_revision = 'd069f4d6b298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pareja', sa.Column('opcion', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pareja', 'opcion')
    # ### end Alembic commands ###
