"""empty message

Revision ID: b3b35e70daab
Revises: 60b4f32027a8
Create Date: 2021-10-06 19:17:54.921784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b35e70daab'
down_revision = '60b4f32027a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pareja_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'tiempo_proceso_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'centro_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'tratamiento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tratamiento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'centro_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'tiempo_proceso_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'pareja_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
