"""empty message

Revision ID: b87fb89576b9
Revises: 4186f52cfc47
Create Date: 2021-10-27 09:44:49.602797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87fb89576b9'
down_revision = '4186f52cfc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'is_mutual')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('is_mutual', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
