"""empty message

Revision ID: d069f4d6b298
Revises: eeb82289824c
Create Date: 2021-10-06 19:11:00.992582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd069f4d6b298'
down_revision = 'eeb82289824c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pareja', 'opcion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pareja', sa.Column('opcion', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
