"""empty message

Revision ID: da6aa2e007c2
Revises: fd47b3a6d97e
Create Date: 2021-10-06 17:58:34.820217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6aa2e007c2'
down_revision = 'fd47b3a6d97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tratamiento_tipo_key', 'tratamiento', type_='unique')
    op.drop_column('tratamiento', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_unique_constraint('tratamiento_tipo_key', 'tratamiento', ['tipo'])
    # ### end Alembic commands ###
