"""empty message

Revision ID: e77900ad7420
Revises: 061510ebfdd1
Create Date: 2021-10-20 17:54:57.666286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77900ad7420'
down_revision = '061510ebfdd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'is_active')
    # ### end Alembic commands ###
