"""empty message

Revision ID: f9ef794e2c5a
Revises: 493a2bf3e014
Create Date: 2021-10-06 19:14:26.094238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ef794e2c5a'
down_revision = '493a2bf3e014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('tipo', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tratamiento', 'tipo')
    # ### end Alembic commands ###
